### PR TITLE
feat: added SelectableColoredText widget

### PR DESCRIPTION
**Pull request by limcheekin**
The `SelectableColoredText` widget allowed user to select text in the console for copy and paste purpose and can set custom color for the `selectedTextColor` and `selectedTextBackgroundColor`.

Please review, merge and publish new version of the `flutter_console_widget`.

Thank you.

### CODE REVIEW

**Comment by limcheekin** [comment]
Thanks for merged the pull request.

Could you publish updated version of the package?

**Comment by semakers** [comment]
@limcheekin  sure!!, just give me few days to get free time to do it :)

**Comment by limcheekin** [comment]
> @limcheekin sure!!, just give me few days to get free time to do it :)

May I know any update?

**Comment by limcheekin** [comment]
@semakers May I know any update?

**Comment by limcheekin** [comment]
@semakers Happy 2024! May I know did you find time to publish the changes?

**Pull request merged**
